In [24]:
import pandas as pd
import pandas.io.sql as psql
import psycopg2 as pg
from sqlalchemy import create_engine

In [35]:
hostname = 'localhost'
port=5432
username = 'postgres'
password = 'zenvisage'
database = 'seedb_data'

continuous=['age', 'restbp', 'chol', 'thalach', 'ca', 'oldpeak']
discrete=['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal']
aggregate=['sum','avg','max','min']

k=10

In [26]:
connection = psycopg2.connect( host=hostname, port = port, user=username, password=password, dbname=database )

In [27]:
def get_query_result( conn, query ) :
    cur = conn.cursor()
    cur.execute( query )
    return cur

In [33]:
q1="select * from heart_disease;"
db = psql.read_sql(q1, connection)

In [34]:
db

,age,sex,cp,restbp,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,64,male,non_anginal_pain,125,309,no_more_than_120,normal,131,exercise_induced_angina,1.8,flat,0,reversable_defect,disease
1,70,male,non_anginal_pain,160,269,no_more_than_120,normal,112,exercise_induced_angina,2.9,flat,1,reversable_defect,disease
2,50,male,non_anginal_pain,140,233,no_more_than_120,normal,163,no_exercise_induced_angina,0.6,flat,1,reversable_defect,disease
3,59,male,non_anginal_pain,126,218,more_than_120,normal,134,no_exercise_induced_angina,2.2,flat,1,fixed defect,disease
4,49,male,non_anginal_pain,120,188,no_more_than_120,normal,139,no_exercise_induced_angina,2.0,flat,3,reversable_defect,disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,55,female,atypical_angina,132,342,no_more_than_120,normal,166,no_exercise_induced_angina,1.2,upsloping,0,normal,no_disease
295,41,male,atypical_angina,120,157,no_more_than_120,normal,182,no_exercise_induced_angina,0.0,upsloping,0,normal,no_disease
296,29,male,atypical_angina,130,204,no_more_than_120,showing_probable,202,no_exercise_induced_angina,0.0,upsloping,0,normal,no_disease
297,55,female,atypical_angina,135,250,no_more_than_120,showing_probable,161,no_exercise_induced_angina,1.4,flat,0,normal,no_disease
298,56,male,atypical_angina,130,221,no_more_than_120,showing_probable,163,no_exercise_induced_angina,0.0,upsloping,0,reversable_defect,no_disease

In [40]:
db.shape

(299, 14)

In [58]:
# Missing
hostname = 'localhost'
port=5432
username = 'postgres'
password = 'zenvisage'
database = 'heart_dataset_random'

connection_missing = psycopg2.connect( host=hostname, port = port, user=username, password=password, dbname=database )

q2="select * from db_30rand_missing_a_m1;"
dbm = psql.read_sql(q2, connection_missing)
dbm.drop(dbm.columns[[0]], axis=1, inplace=True)

In [59]:
dbm

,age,sex,cp,restbp,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,NaN,None,non_anginal_pain,125.0,NaN,no_more_than_120,None,NaN,exercise_induced_angina,NaN,flat,0.0,reversable_defect,disease
1,NaN,male,None,160.0,269.0,no_more_than_120,normal,112.0,exercise_induced_angina,2.9,flat,1.0,reversable_defect,disease
2,NaN,male,non_anginal_pain,NaN,233.0,None,None,163.0,None,0.6,None,NaN,reversable_defect,disease
3,NaN,None,None,126.0,218.0,more_than_120,normal,134.0,no_exercise_induced_angina,2.2,flat,NaN,fixed defect,disease
4,49.0,male,None,120.0,188.0,None,None,139.0,None,2.0,None,3.0,reversable_defect,disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,NaN,female,atypical_angina,NaN,NaN,no_more_than_120,normal,166.0,no_exercise_induced_angina,1.2,upsloping,0.0,None,no_disease
295,41.0,male,None,120.0,NaN,None,None,182.0,None,0.0,upsloping,NaN,normal,no_disease
296,29.0,None,None,NaN,204.0,None,showing_probable,NaN,no_exercise_induced_angina,0.0,None,NaN,normal,no_disease
297,55.0,female,atypical_angina,135.0,250.0,no_more_than_120,showing_probable,161.0,None,NaN,flat,NaN,normal,no_disease
298,56.0,male,atypical_angina,130.0,221.0,no_more_than_120,showing_probable,163.0,no_exercise_induced_angina,0.0,None,0.0,None,no_disease

In [60]:
dbm.shape

(299, 14)

## ['cp', 'thal', 'slope', 'ca', 'oldpeak', 'restbp', 'thalach', '.*', 'chol', 'sum', 'count']

In [61]:
# diatas itu hasi dari k = 10 dari ideal dataset

In [67]:
engine = create_engine(r'postgresql+psycopg2://postgres:zenvisage@localhost:5432/temp_after_ideal_imputation')

## drop cp from dbm impute with ideal cp

In [62]:
dbmcp = dbm.copy()
dbmcp.drop(['cp'], axis=1, inplace=True)

In [63]:
dbmcp

,age,sex,restbp,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,NaN,None,125.0,NaN,no_more_than_120,None,NaN,exercise_induced_angina,NaN,flat,0.0,reversable_defect,disease
1,NaN,male,160.0,269.0,no_more_than_120,normal,112.0,exercise_induced_angina,2.9,flat,1.0,reversable_defect,disease
2,NaN,male,NaN,233.0,None,None,163.0,None,0.6,None,NaN,reversable_defect,disease
3,NaN,None,126.0,218.0,more_than_120,normal,134.0,no_exercise_induced_angina,2.2,flat,NaN,fixed defect,disease
4,49.0,male,120.0,188.0,None,None,139.0,None,2.0,None,3.0,reversable_defect,disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,NaN,female,NaN,NaN,no_more_than_120,normal,166.0,no_exercise_induced_angina,1.2,upsloping,0.0,None,no_disease
295,41.0,male,120.0,NaN,None,None,182.0,None,0.0,upsloping,NaN,normal,no_disease
296,29.0,None,NaN,204.0,None,showing_probable,NaN,no_exercise_induced_angina,0.0,None,NaN,normal,no_disease
297,55.0,female,135.0,250.0,no_more_than_120,showing_probable,161.0,None,NaN,flat,NaN,normal,no_disease
298,56.0,male,130.0,221.0,no_more_than_120,showing_probable,163.0,no_exercise_induced_angina,0.0,None,0.0,None,no_disease

In [65]:
dbmcp['cp'] = db['cp']

In [69]:
dbmcp

,age,sex,restbp,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,cp
0,NaN,None,125.0,NaN,no_more_than_120,None,NaN,exercise_induced_angina,NaN,flat,0.0,reversable_defect,disease,non_anginal_pain
1,NaN,male,160.0,269.0,no_more_than_120,normal,112.0,exercise_induced_angina,2.9,flat,1.0,reversable_defect,disease,non_anginal_pain
2,NaN,male,NaN,233.0,None,None,163.0,None,0.6,None,NaN,reversable_defect,disease,non_anginal_pain
3,NaN,None,126.0,218.0,more_than_120,normal,134.0,no_exercise_induced_angina,2.2,flat,NaN,fixed defect,disease,non_anginal_pain
4,49.0,male,120.0,188.0,None,None,139.0,None,2.0,None,3.0,reversable_defect,disease,non_anginal_pain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,NaN,female,NaN,NaN,no_more_than_120,normal,166.0,no_exercise_induced_angina,1.2,upsloping,0.0,None,no_disease,atypical_angina
295,41.0,male,120.0,NaN,None,None,182.0,None,0.0,upsloping,NaN,normal,no_disease,atypical_angina
296,29.0,None,NaN,204.0,None,showing_probable,NaN,no_exercise_induced_angina,0.0,None,NaN,normal,no_disease,atypical_angina
297,55.0,female,135.0,250.0,no_more_than_120,showing_probable,161.0,None,NaN,flat,NaN,normal,no_disease,atypical_angina
298,56.0,male,130.0,221.0,no_more_than_120,showing_probable,163.0,no_exercise_induced_angina,0.0,None,0.0,None,no_disease,atypical_angina

In [70]:
dbmcp.to_sql('dbmcp', engine)

# cp and thal

In [71]:
dbm_cp_thal = dbmcp.copy()
dbm_cp_thal.drop(['thal'], axis=1, inplace=True)
dbm_cp_thal['thal'] = db['thal']
dbm_cp_thal.to_sql('dbm_cp_thal', engine)

# cp and thal and slope

In [72]:
dbm_cp_thal_slope = dbm_cp_thal.copy()
dbm_cp_thal_slope.drop(['slope'], axis=1, inplace=True)
dbm_cp_thal_slope['slope'] = db['slope']
dbm_cp_thal_slope.to_sql('dbm_cp_thal_slope', engine)

In [73]:
dbmca = dbm.copy()
dbmca.drop(['ca'], axis=1, inplace=True)
dbmca['ca'] = db['ca']
dbmca.to_sql('dbmca', engine)

In [74]:
dbmca_oldpeak = dbmca.copy()
dbmca_oldpeak.drop(['oldpeak'], axis=1, inplace=True)
dbmca_oldpeak['oldpeak'] = db['oldpeak']
dbmca_oldpeak.to_sql('dbmca_oldpeak', engine)

In [75]:
dbmca_oldpeak_restbp = dbmca_oldpeak.copy()
dbmca_oldpeak_restbp.drop(['restbp'], axis=1, inplace=True)
dbmca_oldpeak_restbp['restbp'] = db['restbp']
dbmca_oldpeak_restbp.to_sql('dbmca_oldpeak_restbp', engine)

In [76]:
db6 = dbm_cp_thal_slope.copy()
db6.drop(['ca'], axis=1, inplace=True)
db6.drop(['oldpeak'], axis=1, inplace=True)
db6.drop(['restbp'], axis=1, inplace=True)
db6['ca'] = db['ca']
db6['oldpeak'] = db['oldpeak']
db6['restbp'] = db['restbp']
db6.to_sql('db6', engine)